#!/bin/bash
DB="$(dirname "$0")/../data/todo.db"
INPUT=$(cat)
ID=$(python3 -c "import sys,json; print(json.loads(sys.argv[1])['id'])" "$INPUT")
NOW=$(date +%s)
sqlite3 "$DB" "UPDATE tasks SET status = 'done', completed_at = $NOW WHERE id = $ID"
echo '{"ok":true}'
