#!/bin/bash
DB="$(dirname "$0")/../data/todo.db"
INPUT=$(cat)
python3 -c "
import sys, json, subprocess
d = json.loads(sys.argv[1])
tid = d.pop('id')
sets = []
for k, v in d.items():
    if v is None:
        sets.append(f'{k} = NULL')
    elif isinstance(v, (int, float)):
        sets.append(f'{k} = {v}')
    else:
        safe = str(v).replace(\"'\", \"''\")
        sets.append(f\"{k} = '{safe}'\")
if not sets:
    sys.exit(0)
sql = f\"UPDATE tasks SET {', '.join(sets)} WHERE id = {tid}\"
subprocess.run(['sqlite3', sys.argv[2], sql], check=True)
" "$INPUT" "$DB"
echo '{"ok":true}'
